sudo: required
dist: trusty
addons:
  sonarcloud:
    organization: garethahealy-github
    token:
      secure: fZPvyzTOQrauCHtPDNexD6zi7uAbWZiWvZuKlz6WIv1NS4UmYoIdrd66Z1CssXKqIxxwBCjmtRpXjfvkdGRSRJWoXDEo8cQ4+BSGldhjnRVb//2Hzpuuf82ULvd0KxisWH1Ak+Q3389MBLKIHIsrWgRipFL+dKr3CBNN8HBgsJQ=
env:
  global:
  - secure: kb9p6kiEh9mPkVgg0cCq5abvzjZcgF2W0nLEj7TpkvqrUWEoQ0SufadELXHryJwsuczZ2+PpXEPCdmNUg81jy8P8Yqu44+eVqASvWnK4hcRrwvWI9AreTpvoQs0ZoyoJAVn6HYr0m/jqgFEogo49ekFP0u8hsbGywCY7x7WO5/4=
  - secure: LsUP+cH9gQSUZSrzhzYb9IhtT68sHbuYpg1Qz/h6TdgfDY6npm9p8LGE83EMnsE/VIEIHdDv9T+sLSpWcw0eV9v1rWHORFWsK5038pSZ70f/IOVFad3qAWMRfV3wCeh441C4Ii4wQ8VyVGJI+9fGgeFNlnB1myFMDW/yQgXaYOE=
  - secure: buNv259fFCvGe3v9CcQpBAAcMBEcSEnhZiQJGGekJXGkLCk1knZgA3yVMQW1S+KFXm9CHe/ML3lmFKx1MpFvmog3LasyNDilghwV7j7FTzQkqE35QmVfnyPmo5BlfwKLs6qsXwvHSyS3heQkERg358j0DfPNugyumEjzhhGidxM=
  - secure: NIVPRvZgjMadxsEiobJ5cqNzW+OAfOzJEcOckpnfuar0e2lwtGTPr4VI0eGaQEl/TCbq08b9XWHkT/Bjb/Nt95jJZQ4aQOVl9ejRytB8Z7K/RU6faC6gXXpzpi/G3xvEZvNq2voSU/WZLynUUZnTKYKtk2fCFgIrWDGIzgmSGhs=
language: java
jdk:
- oraclejdk8
before_install:
- bash .travis/deploy-codesigning.sh
install:
- mvn -N io.takari:maven:wrapper -Dmaven=3.5.0
- java -version && javac -version && ./mvnw -version -B
before_script:
- ./mvnw dependency:go-offline -B
script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -B
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
  - $HOME/.sonar/cache
